name: 'Bug report'
about: 'Report a reproducible bug — include steps, expected outcome, and logs.'
title: '[bug] '
labels: ['bug']
body:
  - type: input
    id: summary
    attributes:
      label: 'Summary'
      description: 'One-line summary of the bug.'
      placeholder: 'E.g. Crash when saving settings with empty token'
  - type: textarea
    id: steps
    attributes:
      label: 'Steps to reproduce'
      description: 'Exact, minimal steps to reproduce (commands, inputs, screenshots).'
      placeholder: |-
        1. Start with a fresh DB
        2. Run `pnpm dev`
        3. Navigate to Settings → Save with empty token
  - type: textarea
    id: expected
    attributes:
      label: 'Expected behavior'
      description: 'What you expected to happen.'
  - type: textarea
    id: actual
    attributes:
      label: 'Actual behavior'
      description: 'What happened instead, including error output or stack traces.'
  - type: input
    id: environment
    attributes:
      label: 'Environment'
      description: 'OS, Node/pnpm versions, commit SHA, and other relevant info (no secrets).'
      placeholder: 'e.g. Ubuntu 22.04, Node v20, pnpm v8, commit abc123'
  - type: textarea
    id: logs
    attributes:
      label: 'Relevant logs / traceback'
      description: 'Paste the short, relevant log excerpt or error message.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Pre-submission checklist'
      options:
        - label: 'I reproduced the issue on the latest v1.0.0 branch'
        - label: 'I searched for existing issues and PRs'
        - label: 'I removed any sensitive information from logs'
