name: 'Documentation request'
about: 'Suggest corrections or improvements to documentation or examples.'
title: '[docs] '
labels: ['documentation']
body:
  - type: input
    id: summary
    attributes:
      label: 'Summary'
      description: 'Short summary of the documentation change.'
  - type: textarea
    id: current
    attributes:
      label: 'Current docs (link or excerpt)'
      description: 'URL or quote of the existing documentation to change.'
  - type: textarea
    id: proposed
    attributes:
      label: 'Proposed improvement'
      description: 'Suggested replacement text, code snippets, or screenshots. Be specific.'
  - type: textarea
    id: rationale
    attributes:
      label: 'Rationale'
      description: 'Why this change improves clarity, correctness, or developer experience.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Pre-submission checklist'
      options:
        - label: 'I searched existing docs and issues'
        - label: 'Change is minimally invasive and documented'
