name: 'Documentation request'
about: 'Suggest corrections or improvements to documentation, examples, or guides.'
title: '[docs] '
labels: ['documentation']
body:
  - type: input
    id: summary
    attributes:
      label: 'One-line summary'
      description: 'Short summary of the requested documentation change.'
  - type: textarea
    id: current
    attributes:
      label: 'Current docs (link or excerpt)'
      description: 'URL, file path, or quote of the existing documentation to change.'
  - type: textarea
    id: proposed
    attributes:
      label: 'Proposed improvement'
      description: 'Suggested replacement text, code snippets, or screenshots. Be specific and include file path when applicable.'
  - type: textarea
    id: rationale
    attributes:
      label: 'Rationale'
      description: 'Why this change improves clarity, correctness, or developer experience.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Pre-submission checklist'
      options:
        - label: 'I searched existing docs, issues, and PRs for duplicates'
        - label: 'I included file paths and code examples where applicable'
        - label: 'Small changes include a proposed patch; larger changes have a design doc or discussion'
