name: 'Feature request'
about: 'Propose a new feature or enhancement with motivation and clear acceptance criteria.'
title: '[feature] '
labels: ['enhancement']
body:
  - type: input
    id: summary
    attributes:
      label: 'One-line summary'
      description: 'Brief title for the feature.'
  - type: textarea
    id: motivation
    attributes:
      label: 'Motivation / user story'
      description: 'Who benefits and what problem this solves.'
      placeholder: 'As a <role>, I want <feature> so that <benefit>.'
  - type: textarea
    id: proposal
    attributes:
      label: 'Proposed solution (high level)'
      description: 'Approach, UX changes, APIs, and examples. Keep it high-level; implementation details can go in a linked design doc.'
  - type: textarea
    id: acceptance
    attributes:
      label: 'Acceptance criteria'
      description: 'Concrete criteria that define when the feature is complete (tests, UX states, performance).'
  - type: input
    id: estimate
    attributes:
      label: 'Estimated effort'
      description: 'Rough estimate (e.g., small / medium / large or story points).'
  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives considered'
      description: 'Other approaches and why they were rejected.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Pre-submission checklist'
      options:
        - label: 'I described user impact, migrations, and compatibility'
        - label: 'I considered security implications'
        - label: 'I added acceptance criteria and success metrics'
        - label: 'I attached mockups or a design doc if UI/UX changes are involved'
