name: 'Feature request'
about: 'Propose a new feature or enhancement with motivation and acceptance criteria.'
title: '[feature] '
labels: ['enhancement']
body:
  - type: input
    id: summary
    attributes:
      label: 'Summary'
      description: 'One-line description of the requested feature.'
  - type: textarea
    id: motivation
    attributes:
      label: 'Motivation / user story'
      description: 'Who benefits and what problem this solves. Provide a short user story.'
      placeholder: 'As a <role>, I want <feature> so that <benefit>.'
  - type: textarea
    id: proposal
    attributes:
      label: 'Proposed solution'
      description: 'High-level approach, UX changes, API or schema suggestions, and examples.'
  - type: textarea
    id: alternatives
    attributes:
      label: 'Alternatives considered'
      description: 'Other approaches and why they were rejected.'
  - type: input
    id: impact
    attributes:
      label: 'Impact'
      description: 'Backward-compatibility, migration needs, security, and estimated effort.'
  - type: checkboxes
    id: checklist
    attributes:
      label: 'Pre-submission checklist'
      options:
        - label: 'I described the user impact and migration needs'
        - label: 'I considered security and compatibility'
        - label: 'I included tests or a test plan where applicable'
